CREATE TABLE `company` (
   `id` INT AUTO_INCREMENT,
   `name` VARCHAR(100),
   `phone` VARCHAR(255),
   `cuit` VARCHAR(255),
   `email` VARCHAR(255),
   PRIMARY KEY (`id`)
);

CREATE TABLE `categories` (
   `id` INT AUTO_INCREMENT,
   `name` VARCHAR(255),
   PRIMARY KEY (`id`)
);

CREATE TABLE `flavors` (
   `id` INT AUTO_INCREMENT,
   `name` VARCHAR(255),
   PRIMARY KEY (`id`)
);

CREATE TABLE `users` (
   `id` INT AUTO_INCREMENT,
   `email` VARCHAR(255),
   `password` VARCHAR(255),
   `admin` TINYINT,
   PRIMARY KEY (`id`)
);

CREATE TABLE `products` (
   `id` INT AUTO_INCREMENT,
   `category_id` INT NOT NULL,
   `flavor_id` INT NOT NULL,
   `name` VARCHAR(255),
   `description` TEXT,
   `stock` INT DEFAULT 0,
   `price` FLOAT,
   `status` TINYINT DEFAULT 0,
   `img` VARCHAR(255) DEFAULT 'product-default.png',
   PRIMARY KEY (`id`)
);


ALTER TABLE `products` ADD CONSTRAINT `FK_6d7113d9-fe0e-4948-8290-0c2f270e7b3b` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`)  ;

ALTER TABLE `products` ADD CONSTRAINT `FK_4cedfc01-311c-4e74-b8a0-fd0748f688bf` FOREIGN KEY (`flavor_id`) REFERENCES `flavors`(`id`)  ;


INSERT INTO `categories` (`id`, `name`) VALUES (NULL, 'Tortas');
INSERT INTO `categories` (`id`, `name`) VALUES (NULL, 'Alfajores');
INSERT INTO `categories` (`id`, `name`) VALUES (NULL, 'Postres');

INSERT INTO `flavors` (`id`, `name`) VALUES (NULL, 'Chocolate');
INSERT INTO `flavors` (`id`, `name`) VALUES (NULL, 'Frutilla');
INSERT INTO `flavors` (`id`, `name`) VALUES (NULL, 'Vainilla');
INSERT INTO `flavors` (`id`, `name`) VALUES (NULL, 'Dulce de leche');
INSERT INTO `flavors` (`id`, `name`) VALUES (NULL, 'Coco');

INSERT INTO `company` (`id`, `name`, `phone` , `cuit`, `email`) VALUES (NULL, 'LuanaCake', '+5492995099607', '20-37435348-3','contacto@luanacake.com.ar');

insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (1, 2, 2, 'Oxtail - Cut', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 24, 13.46, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (2, 3, 4, 'Soup Campbells', 'Etiam justo. Etiam pretium iaculis justo.', 7, 16.73, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (3, 3, 3, 'Olives - Nicoise', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 45, 94.95, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (4, 2, 3, 'Onion - Dried', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 30, 12.51, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (5, 1, 5, 'Coffee - Decafenated', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 84, 85.94, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (6, 3, 1, 'Wine - Savigny - Les - Beaune', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 92, 85.98, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (7, 2, 1, 'Beef - Shank', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 56, 42.04, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (8, 2, 4, 'Pear - Halves', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 1, 34.08, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (9, 1, 1, 'Ham - Cooked Italian', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 97, 10.98, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (10, 3, 2, 'Buffalo - Tenderloin', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 13, 95.37, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (11, 2, 2, 'Kirsch - Schloss', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 46, 90.64, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (12, 3, 5, 'Lettuce - Spring Mix', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 9, 10.31, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (13, 1, 5, 'Tea - Decaf Lipton', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 94, 43.48, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (14, 1, 5, 'Juice - Propel Sport', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 59, 40.03, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (15, 3, 2, 'Snails - Large Canned', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 86, 33.8, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (16, 3, 2, 'Cheese - Boursin, Garlic / Herbs', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 64, 61.02, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (17, 1, 2, 'Fiddlehead - Frozen', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 57, 75.01, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (18, 3, 3, 'Wine - Chablis 2003 Champs', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 82, 18.31, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (19, 1, 2, 'Ice - Clear, 300 Lb For Carving', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 71, 52.28, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (20, 3, 3, 'Wine - Alsace Gewurztraminer', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 88, 18.35, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (21, 3, 1, 'Lid Tray - 12in Dome', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 12, 59.84, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (22, 2, 4, 'Bacardi Raspberry', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 92, 33.78, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (23, 2, 1, 'Snapple - Iced Tea Peach', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 17, 5.95, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (24, 3, 4, 'Coke - Diet, 355 Ml', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 10, 41.8, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (25, 3, 1, 'Lamb Rack Frenched Australian', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 11, 13.98, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (26, 3, 2, 'Jello - Assorted', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 57, 35.12, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (27, 3, 3, 'Cake Circle, Paprus', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3, 54.81, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (28, 1, 3, 'Puree - Mocha', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 26, 95.4, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (29, 3, 5, 'Salmon Steak - Cohoe 8 Oz', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 34, 56.7, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (30, 1, 5, 'Compound - Orange', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 65, 49.36, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (31, 1, 4, 'Syrup - Kahlua Chocolate', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 30, 1.07, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (32, 3, 1, 'Water - Spring Water, 355 Ml', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 22, 96.34, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (33, 3, 4, 'Bowl 12 Oz - Showcase 92012', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 82, 16.35, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (34, 1, 2, 'Flour Dark Rye', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 75, 54.7, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (35, 1, 2, 'Wine - Pinot Noir Pond Haddock', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 74, 15.2, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (36, 3, 4, 'The Pop Shoppe - Lime Rickey', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 99, 14.18, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (37, 1, 4, 'Sobe - Cranberry Grapefruit', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 82, 72.41, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (38, 1, 3, 'Beer - Mill St Organic', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 60, 46.97, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (39, 1, 3, 'Arctic Char - Fillets', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 90, 66.3, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (40, 3, 5, 'Salmon - Sockeye Raw', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 2, 55.47, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (41, 1, 3, 'Dragon Fruit', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 7, 86.85, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (42, 3, 1, 'Pepper - Paprika, Spanish', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 39, 73.6, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (43, 2, 4, 'Oil - Cooking Spray', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 60, 39.72, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (44, 3, 3, 'Salt - Celery', 'Sed ante.', 74, 89.93, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (45, 2, 2, 'Trueblue - Blueberry 12x473ml', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 50, 5.66, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (46, 3, 2, 'Carbonated Water - Blackcherry', 'Integer non velit.', 56, 88.3, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (47, 2, 1, 'Beef - Tender Tips', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 43, 8.29, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (48, 2, 5, 'Spaghetti Squash', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 41, 47.31, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (49, 3, 5, 'Wine - Charddonnay Errazuriz', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 84, 64.57, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (50, 1, 2, 'Ecolab Crystal Fusion', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 49, 68.56, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (51, 1, 4, 'Grapefruit - Pink', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 94, 4.92, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (52, 1, 4, 'Fennel - Seeds', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 36, 88.26, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (53, 2, 5, 'Bagelers - Cinn / Brown Sugar', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 65, 35.96, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (54, 3, 4, 'Pasta - Cannelloni, Sheets, Fresh', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 13, 26.72, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (55, 2, 5, 'Pate - Liver', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 26, 12.42, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (56, 2, 3, 'Vermouth - White, Cinzano', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 83, 23.35, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (57, 1, 3, 'Beef - Salted', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 21, 6.21, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (58, 3, 4, 'Napkin - Dinner, White', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 12, 77.41, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (59, 3, 4, 'Beer - Original Organic Lager', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 52, 62.71, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (60, 2, 3, 'Versatainer Nc - 888', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 30, 15.48, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (61, 2, 5, 'Wine - Kwv Chenin Blanc South', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 38, 95.83, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (62, 3, 5, 'Rum - Mount Gay Eclipes', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 48, 85.85, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (63, 1, 1, 'Food Colouring - Orange', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 8, 26.36, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (64, 1, 2, 'Coconut Milk - Unsweetened', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 87, 54.24, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (65, 2, 2, 'Cranberry Foccacia', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 93, 58.34, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (66, 1, 4, 'Extract - Vanilla,artificial', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 43, 91.84, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (67, 1, 3, 'Roe - Lump Fish, Red', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 51, 86.88, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (68, 3, 1, 'Bread - Bistro Sour', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 42, 12.32, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (69, 3, 3, 'Mushroom - Portebello', 'Pellentesque ultrices mattis odio.', 96, 69.2, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (70, 1, 4, 'Zucchini - Yellow', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 89, 29.71, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (71, 2, 1, 'Pomegranates', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 63, 41.75, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (72, 1, 5, 'Parsley - Dried', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 35, 59.71, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (73, 2, 2, 'Pineapple - Canned, Rings', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 81, 82.1, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (74, 1, 3, 'Lettuce - Sea / Sea Asparagus', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 33, 83.72, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (75, 2, 3, 'Fish - Artic Char, Cold Smoked', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 32, 67.46, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (76, 1, 1, 'Wine - White, Concha Y Toro', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 94, 51.36, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (77, 1, 3, 'Lighter - Bbq', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 78, 47.03, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (78, 2, 3, 'Beef Cheek Fresh', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 66, 62.26, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (79, 2, 1, 'Napkin - Cocktail,beige 2 - Ply', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 81, 52.92, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (80, 2, 1, 'Beer - Sleemans Honey Brown', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 28, 54.57, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (81, 3, 1, 'Halibut - Fletches', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 48, 21.17, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (82, 1, 4, 'Oil - Macadamia', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 69, 12.27, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (83, 2, 1, 'Flour - Pastry', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 37, 52.78, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (84, 3, 4, 'Nut - Pistachio, Shelled', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 76, 4.84, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (85, 3, 5, 'Muffin Hinge Container 6', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 15, 56.15, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (86, 1, 4, 'Flour - Teff', 'Aliquam quis turpis eget elit sodales scelerisque.', 16, 1.69, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (87, 2, 4, 'Hold Up Tool Storage Rack', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 33, 54.08, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (88, 3, 4, 'Tart Shells - Sweet, 3', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 15, 1.29, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (89, 3, 3, 'Island Oasis - Sweet And Sour Mix', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 95, 67.44, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (90, 1, 4, 'Nut - Almond, Blanched, Ground', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 44, 31.92, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (91, 2, 2, 'Garlic - Peeled', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 53, 43.74, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (92, 1, 2, 'Chinese Lemon Pork', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 83, 67.09, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (93, 2, 5, 'Wine - Zinfandel California 2002', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 83, 16.93, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (94, 2, 1, 'Soup - Campbells Broccoli', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 85, 6.65, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (95, 1, 4, 'Lemonade - Strawberry, 591 Ml', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 47, 31.88, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (96, 1, 2, 'Soup - Campbells, Chix Gumbo', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 29, 82.54, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (97, 1, 4, 'Ecolab - Hand Soap Form Antibac', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 99, 41.24, true, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (98, 1, 1, 'Eggplant Italian', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 8, 62.0, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (99, 2, 4, 'Coffee Cup 16oz Foam', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 96, 37.36, false, 'product-default.png');
insert into products (id, category_id, flavor_id, name, description, stock, price, status, img) values (100, 2, 5, 'Sponge Cake Mix - Chocolate', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 57, 73.67, false, 'product-default.png');

insert into users (id, email, password, admin) values (1, 'bkenealy0@theguardian.com', 'ySfAbDj', false);
insert into users (id, email, password, admin) values (2, 'ngaythorpe1@jiathis.com', 'tAv5WFuazh', true);
insert into users (id, email, password, admin) values (3, 'vlorrie2@mashable.com', '6NhAaMAmAB', true);
insert into users (id, email, password, admin) values (4, 'fbrou3@dedecms.com', 'mLmCeeK', true);
insert into users (id, email, password, admin) values (5, 'dtomasino4@narod.ru', 'Dmsc8Fut', true);
insert into users (id, email, password, admin) values (6, 'adallyn5@opera.com', 'Uj3Q9D', false);
insert into users (id, email, password, admin) values (7, 'mcleator6@tmall.com', 'pb2XLwn', false);
insert into users (id, email, password, admin) values (8, 'swoodcraft7@youtube.com', 'etz2IdTy', true);
insert into users (id, email, password, admin) values (9, 'esollam8@cbslocal.com', 'splkM99v', true);
insert into users (id, email, password, admin) values (10, 'foldford9@delicious.com', 'QGKY5mOAW1', false);
insert into users (id, email, password, admin) values (11, 'rheritya@zdnet.com', 'PbkPbx3QPJ', true);
insert into users (id, email, password, admin) values (12, 'fkochelb@1und1.de', 'C6mzlN', false);
insert into users (id, email, password, admin) values (13, 'abridgnellc@fc2.com', 'efEItrJrwYn', true);
insert into users (id, email, password, admin) values (14, 'vtettd@domainmarket.com', 'MRDx8Qb', true);
insert into users (id, email, password, admin) values (15, 'wperelle@123-reg.co.uk', 'vaMtUTum', true);
insert into users (id, email, password, admin) values (16, 'fkondratenyaf@wp.com', 'Vjp7yvk2f', true);
insert into users (id, email, password, admin) values (17, 'cbanasikg@freewebs.com', 'g7rBsqf', false);
insert into users (id, email, password, admin) values (18, 'kclymah@ycombinator.com', 'dfUNAYhc', true);
insert into users (id, email, password, admin) values (19, 'cdowlesi@symantec.com', 'w3YF44C', false);
insert into users (id, email, password, admin) values (20, 'adebooj@skype.com', 'Gnb4lklJ5', true);
insert into users (id, email, password, admin) values (21, 'ochatelk@globo.com', 'ZR6uvr9iD', false);
insert into users (id, email, password, admin) values (22, 'mmeachanl@bigcartel.com', 'ZVedlA', false);
insert into users (id, email, password, admin) values (23, 'pmonkemanm@goodreads.com', 'qCgUnZR', true);
insert into users (id, email, password, admin) values (24, 'qstrowann@census.gov', '63HQQyCLMs', true);
insert into users (id, email, password, admin) values (25, 'gvandaaleno@globo.com', '46s1lxkC', true);
insert into users (id, email, password, admin) values (26, 'gthringp@yahoo.co.jp', 'ap4axJYHH', true);
insert into users (id, email, password, admin) values (27, 'brisbridgerq@globo.com', 'IGC6Cy57lMhe', false);
insert into users (id, email, password, admin) values (28, 'apollastroner@quantcast.com', 'Dn0200S3', false);
insert into users (id, email, password, admin) values (29, 'rscarratts@prweb.com', '0qENJuNAZH', true);
insert into users (id, email, password, admin) values (30, 'dtulkt@dedecms.com', 'xWXIlmEjoW', true);